### ISSUE TITLE
Создание модуля

### ISSUE THREAD

**Issue by nicothin** [nicothin/bemform-ui#2]
```
nicothin@nicwin10 MINGW64 /d/projects/bemform-ui/src/_modules (master)
$ node createModuleBundle.js field-text less scss styl
module.js:339
    throw err;
    ^

Error: Cannot find module 'D:\projects\bemform-ui\src\_modules\createModuleBundle.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

nicothin@nicwin10 MINGW64 /d/projects/bemform-ui/src/_modules (master)
$ npm -v
2.14.7

nicothin@nicwin10 MINGW64 /d/projects/bemform-ui/src/_modules (master)
$ node -v
v4.2.1
```

**Comment by aalexeev239** [comment]
@nicothin Вы запускаете скрипт в той папке, в которой его нет. Попробуйте из корня.

**Comment by nicothin** [comment]
Нужно в описании уточнить.
А еще лучше сделать так, чтоб он не зависел от файловой структуры (кажется, все подобные ускорители работают по умолчанию в той папке, в которой их запускают, не?).

**Comment by aalexeev239** [comment]
@nicothin Вы запускаете скрипт в той папке, в которой его нет. Попробуйте из корня.
